"""add_goal_checkins

Revision ID: 02c332a04105
Revises: e083f1630361
Create Date: 2026-01-01 14:22:01.603778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c332a04105'
down_revision = 'e083f1630361'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_checkins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_checkins_id'), 'goal_checkins', ['id'], unique=False)
    op.create_index(op.f('ix_goal_checkins_user_id'), 'goal_checkins', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_checkins_user_id'), table_name='goal_checkins')
    op.drop_index(op.f('ix_goal_checkins_id'), table_name='goal_checkins')
    op.drop_table('goal_checkins')
    # ### end Alembic commands ###

